name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
        
      - name: Install lint dependencies
        run: pip3 install ansible ansible-lint yamllint

      - name: Lint role
        run: |
          ansible-lint
          yamllint .
      
      - name: Test role
        run: |
          echo '[defaults]' > ansible.cfg
          echo 'roles_path = ../' >> ansible.cfg
          ansible-playbook -i localhost, tests/test.yml --syntax-check
          ansible-playbook -i localhost, --connection=local -b tests/test.yml
          ansible-playbook -i localhost, --connection=local -b tests/test.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
          id ansibletestuser  | grep --silent "uid=2222(ansibletestuser) gid=2222(ansibletestuser) groups=2222(ansibletestuser),2(bin),100(users)"
          id ansibletestuser2 | grep --silent "uid=2223(ansibletestuser2) gid=2223(ansibletestuser2) groups=2223(ansibletestuser2),2(bin),100(users)"
          id ansibletestuser3 | grep --silent "uid=2224(ansibletestuser3) gid=4001(ansibletestgroup1) groups=4001(ansibletestgroup1),2(bin),100(users)"
          id ansibletestuser4 | grep --silent "uid=2225(ansibletestuser4) gid=100(users) groups=100(users),2(bin)"
          id ansibletestuser5 | grep --silent "uid=2226(ansibletestuser5) gid=4000(ansibletestgroup) groups=4000(ansibletestgroup),2(bin),100(users)"
          grep --silent "^ansibletestgroup:"  /etc/group
          grep --silent "^ansibletestgroup1:" /etc/group
          ls -lgd /home/ansibletestuser  | awk '{exit $3!="ansibletestuser"}'
          ls -lgd /home/otherdirectory   | awk '{exit $3!="ansibletestuser2"}'
          ls -lgd /home/ansibletestuser3 | awk '{exit $3!="ansibletestgroup1"}'
          ls -lgd /home/otherdirectory1  | awk '{exit $3!="users"}'
          ls -lgd /home/ansibletestuser5 | awk '{exit $3!="ansibletestgroup"}'
          ls -lg /home/ansibletestuser/.profile   | awk '{exit $3!="ansibletestuser"}'
          ls -lg /home/otherdirectory/.profile    | awk '{exit $3!="ansibletestuser2"}'
          ls -lg /home/ansibletestuser3/.profile  | awk '{exit $3!="ansibletestgroup1"}'
          ls -lg /home/otherdirectory1/.profile   | awk '{exit $3!="users"}'
          ls -lgd /home/ansibletestuser5/.profile | awk '{exit $3!="ansibletestgroup"}'
